apiVersion: batch/v1 
kind: Job
metadata:
  name: "{{ .Chart.Name }}-db-migrate"
  annotations:
    "helm.sh/hook": pre-upgrade,pre-install
    "helm.sh/hook-delete-policy": hook-succeeded
spec: 
  activeDeadlineSeconds: 60
  ttlSecondsAfterFinished: 100
  template:
    spec:
      restartPolicy: Never
      containers: 
        - name: "{{ .Chart.Name }}-migration-job"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          command:
            - npx
            - prisma
            - migrate
            - deploy
          env:          
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: helmkube-postgresql
                  key: postgres-password
            - name: DATABASE_URL
              value: "postgresql://postgres:$(DB_PASSWORD)@helmkube-postgresql:5432/postgres?schema=public"